import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { sendEmail } from '@/lib/email'
import { calculateNextReminderDate, parseJsonArray } from '@/lib/compliance'

function isAuthorizedCronRequest(request: NextRequest): boolean {
  const authHeader = request.headers.get('authorization')
  const expectedToken = process.env.CRON_SECRET || 'dev-cron-secret'
  return authHeader === `Bearer ${expectedToken}`
}

async function processReminders() {
  const today = new Date()
  today.setHours(0, 0, 0, 0)

  const items = await prisma.complianceItem.findMany({
    where: {
      status: {
        in: ['OPEN', 'IN_PROGRESS'],
      },
      nextReminderDate: {
        lte: today,
      },
      deadlineDate: {
        gte: today,
      },
      owner: {
        email: {
          not: '',
        },
      },
    },
    include: {
      owner: {
        select: {
          id: true,
          fullName: true,
          email: true,
        },
      },
      category: true,
      club: true,
    },
  })

  const result = {
    checked: items.length,
    sent: 0,
    failed: 0,
    errors: [] as string[],
  }

  for (const item of items) {
    try {
      if (!item.owner?.email) continue

      const reminderSchedule = parseJsonArray<number>(item.reminderSchedule, [])
      if (!reminderSchedule.length) continue

      const daysUntilDue = Math.ceil((item.deadlineDate.getTime() - today.getTime()) / (1000 * 60 * 60 * 24))
      if (!reminderSchedule.includes(daysUntilDue)) continue

      const sentReminders = parseJsonArray<{ sentAt: string; daysBefore: number }>(item.remindersSent, [])
      const alreadySent = sentReminders.some(
        (entry) => entry.daysBefore === daysUntilDue && new Date(entry.sentAt).toDateString() === today.toDateString()
      )
      if (alreadySent) continue

      const subject = `Compliance Reminder: ${item.title} due in ${daysUntilDue} day${daysUntilDue === 1 ? '' : 's'}`
      const htmlContent = `
        <div style="font-family: Arial, sans-serif; max-width: 620px; margin: 0 auto;">
          <h2 style="color: #1f2937;">Compliance Reminder</h2>
          <p>Hello ${item.owner.fullName},</p>
          <p>This compliance requirement is due in <strong>${daysUntilDue} day${daysUntilDue === 1 ? '' : 's'}</strong>.</p>
          <div style="border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; background: #f9fafb;">
            <p style="margin: 0 0 8px;"><strong>Item:</strong> ${item.title}</p>
            <p style="margin: 0 0 8px;"><strong>Category:</strong> ${item.category?.name || 'Uncategorised'}</p>
            <p style="margin: 0 0 8px;"><strong>Deadline:</strong> ${item.deadlineDate.toLocaleDateString('en-AU')}</p>
            ${item.notes ? `<p style="margin: 0;"><strong>Notes:</strong> ${item.notes}</p>` : ''}
          </div>
          <p style="margin-top: 16px; color: #6b7280; font-size: 13px;">Generated by ICGymHub Compliance Manager for ${item.club.name}.</p>
        </div>
      `

      await sendEmail({
        to: item.owner.email,
        subject,
        htmlContent,
      })

      const nextReminderDate = calculateNextReminderDate(item.deadlineDate, reminderSchedule, new Date(today.getTime() + 24 * 60 * 60 * 1000))

      sentReminders.push({
        sentAt: today.toISOString(),
        daysBefore: daysUntilDue,
      })

      await prisma.complianceItem.update({
        where: { id: item.id },
        data: {
          remindersSent: JSON.stringify(sentReminders),
          lastReminderSent: today,
          nextReminderDate,
        },
      })

      result.sent += 1
    } catch (error) {
      result.failed += 1
      result.errors.push(`Item ${item.id}: ${error instanceof Error ? error.message : 'Unknown error'}`)
    }
  }

  return result
}

export async function GET(request: NextRequest) {
  try {
    if (!isAuthorizedCronRequest(request)) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const result = await processReminders()

    return NextResponse.json({
      success: true,
      ...result,
      timestamp: new Date().toISOString(),
    })
  } catch (error) {
    console.error('Compliance reminder processing error:', error)
    return NextResponse.json({ error: 'Failed to process compliance reminders' }, { status: 500 })
  }
}

export async function POST(request: NextRequest) {
  return GET(request)
}
