import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { sendEmail, getLogoHeaderHtml } from '@/lib/email'
import { calculateNextReminderDate, parseJsonArray } from '@/lib/compliance'

function isAuthorizedCronRequest(request: NextRequest): boolean {
  const authHeader = request.headers.get('authorization')
  const expectedToken = process.env.CRON_SECRET || 'dev-cron-secret'
  return authHeader === `Bearer ${expectedToken}`
}

async function processReminders() {
  const today = new Date()
  today.setHours(0, 0, 0, 0)

  const items = await prisma.complianceItem.findMany({
    where: {
      status: {
        in: ['OPEN', 'IN_PROGRESS'],
      },
      nextReminderDate: {
        lte: today,
      },
      deadlineDate: {
        gte: today,
      },
      owner: {
        email: {
          not: '',
        },
      },
    },
    include: {
      owner: {
        select: {
          id: true,
          fullName: true,
          email: true,
        },
      },
      category: true,
      club: true,
    },
  })

  const result = {
    checked: items.length,
    sent: 0,
    failed: 0,
    errors: [] as string[],
  }

  for (const item of items) {
    try {
      if (!item.owner?.email) continue

      const reminderSchedule = parseJsonArray<number>(item.reminderSchedule, [])
      if (!reminderSchedule.length) continue

      const daysUntilDue = Math.ceil((item.deadlineDate.getTime() - today.getTime()) / (1000 * 60 * 60 * 24))
      if (!reminderSchedule.includes(daysUntilDue)) continue

      const sentReminders = parseJsonArray<{ sentAt: string; daysBefore: number }>(item.remindersSent, [])
      const alreadySent = sentReminders.some(
        (entry) => entry.daysBefore === daysUntilDue && new Date(entry.sentAt).toDateString() === today.toDateString()
      )
      if (alreadySent) continue

      const subject = `Compliance Reminder: ${item.title} due in ${daysUntilDue} day${daysUntilDue === 1 ? '' : 's'}`
      const htmlContent = `
        <!DOCTYPE html>
        <html>
        <head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
        <body style="margin:0;padding:0;font-family:Arial,sans-serif;background-color:#f4f4f4;">
          <table role="presentation" style="width:100%;border-collapse:collapse;">
            <tr>
              <td style="padding:40px 0;text-align:center;">
                <table role="presentation" style="width:620px;margin:0 auto;background-color:#ffffff;border-radius:8px;box-shadow:0 2px 4px rgba(0,0,0,0.1);">
                  ${getLogoHeaderHtml()}
                  <tr>
                    <td style="padding:30px;text-align:center;background-color:#2563eb;">
                      <h1 style="margin:0;color:#ffffff;font-size:24px;">Compliance Reminder</h1>
                    </td>
                  </tr>
                  <tr>
                    <td style="padding:30px;">
                      <p style="margin:0 0 16px;font-size:16px;color:#333;">Hello ${item.owner.fullName},</p>
                      <p style="margin:0 0 20px;font-size:16px;color:#333;">This compliance requirement is due in <strong>${daysUntilDue} day${daysUntilDue === 1 ? '' : 's'}</strong>.</p>
                      <table style="width:100%;border:1px solid #e5e7eb;border-radius:8px;font-size:14px;border-collapse:separate;overflow:hidden;">
                        <tr><td style="padding:10px 12px;color:#666;background:#f9fafb;width:35%;border-bottom:1px solid #e5e7eb;"><strong>Item</strong></td><td style="padding:10px 12px;color:#333;border-bottom:1px solid #e5e7eb;">${item.title}</td></tr>
                        <tr><td style="padding:10px 12px;color:#666;background:#f9fafb;border-bottom:1px solid #e5e7eb;"><strong>Category</strong></td><td style="padding:10px 12px;color:#333;border-bottom:1px solid #e5e7eb;">${item.category?.name || 'Uncategorised'}</td></tr>
                        <tr><td style="padding:10px 12px;color:#666;background:#f9fafb;${item.notes ? 'border-bottom:1px solid #e5e7eb;' : ''}"><strong>Deadline</strong></td><td style="padding:10px 12px;color:#333;${item.notes ? 'border-bottom:1px solid #e5e7eb;' : ''}">${item.deadlineDate.toLocaleDateString('en-AU')}</td></tr>
                        ${item.notes ? `<tr><td style="padding:10px 12px;color:#666;background:#f9fafb;"><strong>Notes</strong></td><td style="padding:10px 12px;color:#333;">${item.notes}</td></tr>` : ''}
                      </table>
                    </td>
                  </tr>
                  <tr>
                    <td style="padding:20px 30px;background-color:#f9fafb;border-radius:0 0 8px 8px;text-align:center;">
                      <p style="margin:0;font-size:12px;color:#6b7280;">Generated by GymHub Compliance Manager for ${item.club.name}.</p>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
          </table>
        </body>
        </html>
      `

      await sendEmail({
        to: item.owner.email,
        subject,
        htmlContent,
      })

      const nextReminderDate = calculateNextReminderDate(item.deadlineDate, reminderSchedule, new Date(today.getTime() + 24 * 60 * 60 * 1000))

      sentReminders.push({
        sentAt: today.toISOString(),
        daysBefore: daysUntilDue,
      })

      await prisma.complianceItem.update({
        where: { id: item.id },
        data: {
          remindersSent: JSON.stringify(sentReminders),
          lastReminderSent: today,
          nextReminderDate,
        },
      })

      result.sent += 1
    } catch (error) {
      result.failed += 1
      result.errors.push(`Item ${item.id}: ${error instanceof Error ? error.message : 'Unknown error'}`)
    }
  }

  return result
}

export async function GET(request: NextRequest) {
  try {
    if (!isAuthorizedCronRequest(request)) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const result = await processReminders()

    return NextResponse.json({
      success: true,
      ...result,
      timestamp: new Date().toISOString(),
    })
  } catch (error) {
    console.error('Compliance reminder processing error:', error)
    return NextResponse.json({ error: 'Failed to process compliance reminders' }, { status: 500 })
  }
}

export async function POST(request: NextRequest) {
  return GET(request)
}
